/**
  ******************************************************************************
  * @file           : master_password_credentials.h
  * @brief          : Generated master-password verifier for the management API.
  * @project        : STM32F767 Health Check
  * @platform       : STMicroelectronics STM32F767ZIT6
  ******************************************************************************
  * @attention
  *
  * Generated by tools/generate_master_verifier.py.
  * This file contains no plaintext password.
  *
  ******************************************************************************
  */

#ifndef MASTER_PASSWORD_CREDENTIALS_H
#define MASTER_PASSWORD_CREDENTIALS_H

#include <stdint.h>

#define MASTER_PASSWORD_PBKDF2_ITERATIONS 100000U
#define MASTER_PASSWORD_VERIFIER_SIZE     32U

static const uint8_t masterPasswordSalt[16] = {
  0x1AU, 0x5FU, 0x0FU, 0x46U, 0x20U, 0xA7U, 0x35U, 0x14U, 0x88U, 0x21U, 0xB6U, 0x29U, 0x93U, 0x36U, 0x94U, 0xD5U
};

static const uint8_t masterPasswordVerifier[32] = {
  0x1AU, 0xE4U, 0x1BU, 0x9FU, 0x34U, 0x97U, 0x71U, 0x88U, 0xDAU, 0xFDU, 0x59U, 0xC3U, 0xC0U, 0xACU, 0x56U, 0xC5U, 0x44U, 0xA1U, 0x1AU, 0x73U, 0x93U, 0x40U, 0x6DU, 0xCBU, 0xC1U, 0xC0U, 0xD4U, 0xF2U, 0x5AU, 0x98U, 0x79U, 0x8AU
};

#endif /* MASTER_PASSWORD_CREDENTIALS_H */
