#!/usr/bin/env python3
"""Generate a C header containing a salted master-password verifier."""

from __future__ import annotations

import argparse
import getpass
import hashlib
import os
from pathlib import Path


DEFAULT_ITERATIONS = 100_000
SALT_SIZE = 16
VERIFIER_SIZE = 32


def format_array(name: str, data: bytes) -> str:
    values = ", ".join(f"0x{value:02X}U" for value in data)
    return (
        f"static const uint8_t {name}[{len(data)}] = {{\n"
        f"  {values}\n"
        "};"
    )


def build_header(salt: bytes, verifier: bytes, iterations: int) -> str:
    return f"""\
/**
  ******************************************************************************
  * @file           : master_password_credentials.h
  * @brief          : Generated master-password verifier for the management API.
  * @project        : STM32F767 Health Check
  * @platform       : STMicroelectronics STM32F767VET6
  ******************************************************************************
  * @attention
  *
  * Generated by tools/generate_master_verifier.py.
  * This file contains no plaintext password.
  *
  ******************************************************************************
  */

#ifndef MASTER_PASSWORD_CREDENTIALS_H
#define MASTER_PASSWORD_CREDENTIALS_H

#include <stdint.h>

#define MASTER_PASSWORD_PBKDF2_ITERATIONS {iterations}U
#define MASTER_PASSWORD_VERIFIER_SIZE     {len(verifier)}U

{format_array("masterPasswordSalt", salt)}

{format_array("masterPasswordVerifier", verifier)}

#endif /* MASTER_PASSWORD_CREDENTIALS_H */
"""


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Prompt for a master password and generate its "
            "PBKDF2-HMAC-SHA-256 verifier."
        )
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("Core/Inc/master_password_credentials.h"),
        help="generated C header path",
    )
    parser.add_argument(
        "--iterations",
        type=int,
        default=DEFAULT_ITERATIONS,
        help="PBKDF2 iteration count",
    )
    return parser.parse_args()


def main() -> int:
    arguments = parse_arguments()
    if arguments.iterations < 10_000:
        raise SystemExit("iteration count must be at least 10000")

    password = getpass.getpass("Master password: ")
    confirmation = getpass.getpass("Confirm master password: ")
    if not password:
        raise SystemExit("master password must not be empty")
    if password != confirmation:
        raise SystemExit("passwords do not match")

    password_bytes = bytearray(password.encode("utf-8"))
    try:
        salt = os.urandom(SALT_SIZE)
        verifier = hashlib.pbkdf2_hmac(
            "sha256",
            password_bytes,
            salt,
            arguments.iterations,
            dklen=VERIFIER_SIZE,
        )
        arguments.output.parent.mkdir(parents=True, exist_ok=True)
        arguments.output.write_text(
            build_header(salt, verifier, arguments.iterations),
            encoding="utf-8",
        )
        arguments.output.chmod(0o600)
    finally:
        password_bytes[:] = b"\x00" * len(password_bytes)

    print(f"Wrote verifier to {arguments.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

